import { CalculatorConfig } from './types';
export const geometryCalculators: CalculatorConfig[]=[
{id:'circle-area',slug:'circle-area',title:'Circle Area & Circumference',description:'Calculate the area and circumference of a circle.',category:'geometry',icon:'Calculator',fields:[{id:'r',label:'Radius',type:'number',defaultValue:5}],calculate:i=>{const r=Math.max(0,Number(i.r)||0);return[{label:'Area',value:Math.PI*r*r,type:'number',highlight:true},{label:'Circumference',value:2*Math.PI*r,type:'number'}]},formula:'A = πr²; C = 2πr',explanation:'Uses the radius to calculate the area enclosed by a circle and its circumference.'},
{id:'triangle-area',slug:'triangle-area',title:'Triangle Area',description:'Calculate the area of a triangle from base and height.',category:'geometry',icon:'Calculator',fields:[{id:'base',label:'Base',type:'number',defaultValue:10},{id:'height',label:'Height',type:'number',defaultValue:6}],calculate:i=>{const b=Number(i.base)||0,h=Number(i.height)||0;return[{label:'Area',value:b*h/2,type:'number',highlight:true}]},formula:'A = (base × height) / 2',explanation:'The area of a triangle is half the area of a rectangle with the same base and height.'},
{id:'rectangle-area',slug:'rectangle-area',title:'Rectangle Area & Perimeter',description:'Calculate the area and perimeter of a rectangle.',category:'geometry',icon:'Calculator',fields:[{id:'width',label:'Width',type:'number',defaultValue:10},{id:'height',label:'Height',type:'number',defaultValue:5}],calculate:i=>{const w=Number(i.width)||0,h=Number(i.height)||0;return[{label:'Area',value:w*h,type:'number',highlight:true},{label:'Perimeter',value:2*(w+h),type:'number'}]},formula:'A = w × h; P = 2(w + h)',explanation:'Multiplies width by height for area and adds all four sides for perimeter.'},
{id:'trapezoid-area',slug:'trapezoid-area',title:'Trapezoid Area',description:'Calculate the area of a trapezoid from its bases and height.',category:'geometry',icon:'Calculator',fields:[{id:'a',label:'Base A',type:'number',defaultValue:12},{id:'b',label:'Base B',type:'number',defaultValue:8},{id:'height',label:'Height',type:'number',defaultValue:5}],calculate:i=>{const a=Number(i.a)||0,b=Number(i.b)||0,h=Number(i.height)||0;return[{label:'Area',value:(a+b)*h/2,type:'number',highlight:true}]},formula:'A = (a + b)h / 2',explanation:'A trapezoid area is the average of its parallel bases multiplied by its height.'},
{id:'pythagorean-theorem',slug:'pythagorean-theorem',title:'Pythagorean Theorem',description:'Find the missing side of a right triangle.',category:'geometry',icon:'Scale',fields:[{id:'a',label:'Leg A',type:'number',defaultValue:3},{id:'b',label:'Leg B',type:'number',defaultValue:4}],calculate:i=>{const a=Number(i.a)||0,b=Number(i.b)||0;return[{label:'Hypotenuse',value:Math.hypot(a,b),type:'number',highlight:true}]},formula:'c = √(a² + b²)',explanation:'For a right triangle, the square of the hypotenuse equals the sum of the squares of the two legs.'},
{id:'distance-points',slug:'distance-points',title:'Distance Between Points',description:'Calculate the Euclidean distance between two points.',category:'geometry',icon:'Scale',fields:[{id:'x1',label:'X₁',type:'number',defaultValue:1},{id:'y1',label:'Y₁',type:'number',defaultValue:2},{id:'x2',label:'X₂',type:'number',defaultValue:5},{id:'y2',label:'Y₂',type:'number',defaultValue:5}],calculate:i=>{const x1=Number(i.x1)||0,y1=Number(i.y1)||0,x2=Number(i.x2)||0,y2=Number(i.y2)||0;return[{label:'Distance',value:Math.hypot(x2-x1,y2-y1),type:'number',highlight:true}]},formula:'d = √[(x₂-x₁)² + (y₂-y₁)²]',explanation:'Measures the straight-line distance between two points on a coordinate plane.'},
{id:'sphere',slug:'sphere',title:'Sphere Volume & Surface Area',description:'Calculate the volume and surface area of a sphere.',category:'geometry',icon:'Calculator',fields:[{id:'r',label:'Radius',type:'number',defaultValue:5}],calculate:i=>{const r=Math.max(0,Number(i.r)||0);return[{label:'Volume',value:4/3*Math.PI*r**3,type:'number',highlight:true},{label:'Surface Area',value:4*Math.PI*r*r,type:'number'}]},formula:'V = 4πr³/3; A = 4πr²',explanation:'Uses the radius to calculate the volume enclosed by a sphere and its surface area.'},
{id:'cylinder',slug:'cylinder',title:'Cylinder Volume & Surface Area',description:'Calculate the volume and surface area of a cylinder.',category:'geometry',icon:'Calculator',fields:[{id:'r',label:'Radius',type:'number',defaultValue:3},{id:'h',label:'Height',type:'number',defaultValue:10}],calculate:i=>{const r=Math.max(0,Number(i.r)||0),h=Math.max(0,Number(i.h)||0);return[{label:'Volume',value:Math.PI*r*r*h,type:'number',highlight:true},{label:'Total Surface Area',value:2*Math.PI*r*(r+h),type:'number'}]},formula:'V = πr²h; A = 2πr(r+h)',explanation:'Calculates the volume and total surface area of a cylinder from its radius and height.'},
{id:'cone',slug:'cone',title:'Cone Volume',description:'Calculate the volume of a cone from radius and height.',category:'geometry',icon:'Calculator',fields:[{id:'r',label:'Radius',type:'number',defaultValue:4},{id:'h',label:'Height',type:'number',defaultValue:9}],calculate:i=>{const r=Math.max(0,Number(i.r)||0),h=Math.max(0,Number(i.h)||0);return[{label:'Volume',value:Math.PI*r*r*h/3,type:'number',highlight:true},{label:'Slant Height',value:Math.hypot(r,h),type:'number'}]},formula:'V = πr²h/3',explanation:'A cone has one third the volume of a cylinder with the same base and height.'},
{id:'polygon-interior-angle',slug:'polygon-interior-angle',title:'Regular Polygon Angles',description:'Calculate the interior angle and angle sum of a regular polygon.',category:'geometry',icon:'Scale',fields:[{id:'n',label:'Number of Sides',type:'number',defaultValue:6,min:3,step:1}],calculate:i=>{const n=Math.max(3,Math.trunc(Number(i.n)||3));return[{label:'Interior Angle',value:(n-2)*180/n,type:'number',highlight:true},{label:'Sum of Interior Angles',value:(n-2)*180,type:'number'}]},formula:'Angle sum = (n - 2) × 180°',explanation:'For a regular polygon, divide the interior-angle sum equally among all sides.'},
  {id:'rectangular-prism',slug:'rectangular-prism',title:'Rectangular Prism',description:'Calculate volume and surface area of a rectangular prism.',category:'geometry',icon:'Calculator',fields:[{id:'l',label:'Length',type:'number',defaultValue:10},{id:'w',label:'Width',type:'number',defaultValue:5},{id:'h',label:'Height',type:'number',defaultValue:3}],calculate:i=>{const l=Number(i.l)||0,w=Number(i.w)||0,h=Number(i.h)||0;return[{label:'Volume',value:l*w*h,type:'number',highlight:true},{label:'Surface Area',value:2*(l*w+l*h+w*h),type:'number'}]},formula:'V = lwh; A = 2(lw + lh + wh)',explanation:'Multiplies the three dimensions for volume and sums the areas of all six faces for surface area.'},
  {id:'arc-length',slug:'arc-length',title:'Arc Length',description:'Calculate the length of a circular arc from radius and angle.',category:'geometry',icon:'Calculator',fields:[{id:'r',label:'Radius',type:'number',defaultValue:10},{id:'angle',label:'Central Angle (°)',type:'number',defaultValue:90}],calculate:i=>{const r=Math.max(0,Number(i.r)||0),a=Number(i.angle)||0;return[{label:'Arc Length',value:r*a*Math.PI/180,type:'number',highlight:true}]},formula:'L = rθ (θ in radians)',explanation:'Converts the central angle to radians and multiplies it by the radius.'},
  {id:'sector-area',slug:'sector-area',title:'Sector Area',description:'Calculate the area of a circular sector.',category:'geometry',icon:'Calculator',fields:[{id:'r',label:'Radius',type:'number',defaultValue:10},{id:'angle',label:'Central Angle (°)',type:'number',defaultValue:90}],calculate:i=>{const r=Math.max(0,Number(i.r)||0),a=Number(i.angle)||0;return[{label:'Sector Area',value:Math.PI*r*r*a/360,type:'number',highlight:true}]},formula:'A = (θ/360°)πr²',explanation:'Calculates the fraction of a circle represented by the sector angle.'},
  {id:'regular-polygon-area',slug:'regular-polygon-area',title:'Regular Polygon Area',description:'Calculate the area of a regular polygon from side length and number of sides.',category:'geometry',icon:'Scale',fields:[{id:'n',label:'Number of Sides',type:'number',defaultValue:6,min:3,step:1},{id:'side',label:'Side Length',type:'number',defaultValue:5}],calculate:i=>{const n=Math.max(3,Math.trunc(Number(i.n)||3)),side=Math.max(0,Number(i.side)||0),apothem=side/(2*Math.tan(Math.PI/n)),area=n*side*apothem/2;return[{label:'Area',value:area,type:'number',highlight:true},{label:'Apothem',value:apothem,type:'number'}]},formula:'A = (perimeter × apothem) / 2',explanation:'Finds the apothem of a regular polygon and multiplies half the perimeter by it.'},

];
