import { CalculatorConfig } from './types';
const fields=[{id:'v1',label:'Value 1',type:'number' as const,defaultValue:10},{id:'v2',label:'Value 2',type:'number' as const,defaultValue:12},{id:'v3',label:'Value 3',type:'number' as const,defaultValue:15},{id:'v4',label:'Value 4',type:'number' as const,defaultValue:18},{id:'v5',label:'Value 5',type:'number' as const,defaultValue:20},{id:'v6',label:'Value 6',type:'number' as const,defaultValue:25}];
const vals=(i:Record<string,any>)=>fields.map(f=>Number(i[f.id])||0);
export const statisticsCalculators: CalculatorConfig[]=[
{id:'median',slug:'median',title:'Median',description:'Find the middle value of a data set.',category:'statistics',icon:'Scale',fields,calculate:i=>{const v=vals(i).sort((a,b)=>a-b);return[{label:'Median',value:(v[2]+v[3])/2,type:'number',highlight:true}]},formula:'Sort values and take the middle value (or average the two middle values).',explanation:'The median is the central value after sorting the data.'},
{id:'mode',slug:'mode',title:'Mode',description:'Find the most frequent value in a data set.',category:'statistics',icon:'PieChart',fields,calculate:i=>{const f=new Map<number,number>();vals(i).forEach(x=>f.set(x,(f.get(x)||0)+1));const max=Math.max(...f.values()),m=[...f.entries()].filter(([,n])=>n===max).map(([x])=>x);return[{label:'Mode',value:m.join(', '),type:'text',highlight:true},{label:'Frequency',value:max,type:'number'}]},explanation:'The mode is the value or values that occur most frequently.'},
{id:'range',slug:'range',title:'Range',description:'Calculate the difference between the maximum and minimum values.',category:'statistics',icon:'Scale',fields,calculate:i=>{const v=vals(i),min=Math.min(...v),max=Math.max(...v);return[{label:'Range',value:max-min,type:'number',highlight:true},{label:'Minimum',value:min,type:'number'},{label:'Maximum',value:max,type:'number'}]},formula:'Range = maximum - minimum',explanation:'The range measures the spread from the smallest to the largest value.'},
{id:'variance',slug:'variance',title:'Variance',description:'Calculate population variance for a data set.',category:'statistics',icon:'Calculator',fields,calculate:i=>{const v=vals(i),m=v.reduce((a,b)=>a+b,0)/v.length;return[{label:'Variance',value:v.reduce((s,x)=>s+(x-m)**2,0)/v.length,type:'number',highlight:true},{label:'Mean',value:m,type:'number'}]},formula:'σ² = Σ(x - μ)² / N',explanation:'Population variance is the average squared distance from the mean.'},
{id:'standard-deviation',slug:'standard-deviation',title:'Standard Deviation',description:'Measure how spread out values are around their mean.',category:'statistics',icon:'TrendingUp',fields,calculate:i=>{const v=vals(i),m=v.reduce((a,b)=>a+b,0)/v.length,variance=v.reduce((s,x)=>s+(x-m)**2,0)/v.length;return[{label:'Standard Deviation',value:Math.sqrt(variance),type:'number',highlight:true},{label:'Mean',value:m,type:'number'}]},formula:'σ = √[Σ(x - μ)² / N]',explanation:'Standard deviation is the square root of variance and expresses typical dispersion in the original units.'},
{id:'coefficient-variation',slug:'coefficient-variation',title:'Coefficient of Variation',description:'Compare relative variability between data sets.',category:'statistics',icon:'Percent',fields,calculate:i=>{const v=vals(i),m=v.reduce((a,b)=>a+b,0)/v.length,sd=Math.sqrt(v.reduce((s,x)=>s+(x-m)**2,0)/v.length);return[{label:'Coefficient of Variation',value:m?sd/m*100:0,type:'percent',highlight:true},{label:'Standard Deviation',value:sd,type:'number'},{label:'Mean',value:m,type:'number'}]},formula:'CV = (standard deviation / mean) × 100',explanation:'The coefficient of variation expresses dispersion relative to the mean.'},
{id:'z-score',slug:'z-score',title:'Z-Score',description:'Calculate how many standard deviations a value is from the mean.',category:'statistics',icon:'Scale',fields:[{id:'x',label:'Value (x)',type:'number',defaultValue:85},{id:'mean',label:'Mean (μ)',type:'number',defaultValue:70},{id:'sd',label:'Standard Deviation (σ)',type:'number',defaultValue:10}],calculate:i=>{const x=Number(i.x)||0,m=Number(i.mean)||0,sd=Number(i.sd)||0;return[{label:'Z-Score',value:sd?(x-m)/sd:0,type:'number',highlight:true}]},formula:'z = (x - μ) / σ',explanation:'A z-score tells you how far a value is from the mean in standard deviation units.'},
{id:'percentile-rank',slug:'percentile-rank',title:'Percentile Rank',description:'Estimate the percentile position of a value within a data set.',category:'statistics',icon:'Percent',fields:[...fields,{id:'x',label:'Target Value',type:'number',defaultValue:18}],calculate:i=>{const v=vals(i),x=Number(i.x)||0,below=v.filter(n=>n<x).length,equal=v.filter(n=>n===x).length;return[{label:'Estimated Percentile',value:(below+0.5*equal)/v.length*100,type:'percent',highlight:true}]},explanation:'This estimate places the target value relative to the values in the supplied data set.'},
{id:'quartiles-iqr',slug:'quartiles-iqr',title:'Quartiles & IQR',description:'Calculate Q1, Q3 and the interquartile range.',category:'statistics',icon:'PieChart',fields,calculate:i=>{const v=vals(i).sort((a,b)=>a-b),med=(a:number[])=>a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2,q1=med(v.slice(0,3)),q3=med(v.slice(3));return[{label:'Q1',value:q1,type:'number'},{label:'Q3',value:q3,type:'number'},{label:'Interquartile Range',value:q3-q1,type:'number',highlight:true}]},formula:'IQR = Q3 - Q1',explanation:'Quartiles split ordered data into four parts; the IQR captures the middle 50%.'},
{id:'correlation',slug:'correlation',title:'Correlation',description:'Estimate the Pearson correlation between two paired variables.',category:'statistics',icon:'TrendingUp',fields:[{id:'x1',label:'X1',type:'number',defaultValue:1},{id:'y1',label:'Y1',type:'number',defaultValue:2},{id:'x2',label:'X2',type:'number',defaultValue:2},{id:'y2',label:'Y2',type:'number',defaultValue:4},{id:'x3',label:'X3',type:'number',defaultValue:3},{id:'y3',label:'Y3',type:'number',defaultValue:5},{id:'x4',label:'X4',type:'number',defaultValue:4},{id:'y4',label:'Y4',type:'number',defaultValue:4}],calculate:i=>{const xs=[1,2,3,4].map(n=>Number(i[`x${n}`])||0),ys=[1,2,3,4].map(n=>Number(i[`y${n}`])||0),mx=xs.reduce((a,b)=>a+b,0)/4,my=ys.reduce((a,b)=>a+b,0)/4,num=xs.reduce((s,x,n)=>s+(x-mx)*(ys[n]-my),0),dx=Math.sqrt(xs.reduce((s,x)=>s+(x-mx)**2,0)),dy=Math.sqrt(ys.reduce((s,y)=>s+(y-my)**2,0));return[{label:'Pearson Correlation (r)',value:dx&&dy?num/(dx*dy):0,type:'number',highlight:true}]},formula:'r = covariance(X,Y) / (σx × σy)',explanation:'Pearson correlation ranges from -1 to 1 and measures linear association between two variables.'},
  {id:'sample-variance',slug:'sample-variance',title:'Sample Variance',description:'Calculate variance using the sample correction (n - 1).',category:'statistics',icon:'Calculator',fields,calculate:i=>{const v=vals(i),m=v.reduce((a,b)=>a+b,0)/v.length;return[{label:'Sample Variance',value:v.length>1?v.reduce((s,x)=>s+(x-m)**2,0)/(v.length-1):0,type:'number',highlight:true}]},formula:'s² = Σ(x - x̄)² / (n - 1)',explanation:'Sample variance uses n - 1 in the denominator to estimate population variance from a sample.'},
  {id:'covariance',slug:'covariance',title:'Covariance',description:'Measure how two variables move together.',category:'statistics',icon:'TrendingUp',fields:[{id:'x1',label:'X1',type:'number',defaultValue:1},{id:'y1',label:'Y1',type:'number',defaultValue:2},{id:'x2',label:'X2',type:'number',defaultValue:2},{id:'y2',label:'Y2',type:'number',defaultValue:3},{id:'x3',label:'X3',type:'number',defaultValue:3},{id:'y3',label:'Y3',type:'number',defaultValue:5},{id:'x4',label:'X4',type:'number',defaultValue:4},{id:'y4',label:'Y4',type:'number',defaultValue:7}],calculate:i=>{const xs=[1,2,3,4].map(n=>Number(i[`x${n}`])||0),ys=[1,2,3,4].map(n=>Number(i[`y${n}`])||0),mx=xs.reduce((a,b)=>a+b,0)/4,my=ys.reduce((a,b)=>a+b,0)/4;return[{label:'Covariance',value:xs.reduce((s,x,n)=>s+(x-mx)*(ys[n]-my),0)/4,type:'number',highlight:true}]},formula:'Cov(X,Y) = Σ[(x - μx)(y - μy)] / N',explanation:'Positive covariance means the variables tend to move together; negative covariance means they tend to move in opposite directions.'},

];
